name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [android, ios]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
    - name: Install Flutter
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.24.3' # Update with your Flutter version 

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android
      if: matrix.platform == 'android'
      run: flutter build apk --release

    - name: Build iOS
      if: matrix.platform == 'ios'
      run: flutter build ios --release --no-codesign

    - name: Upload Android APK
      if: matrix.platform == 'android'
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload iOS build
      if: matrix.platform == 'ios'
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: build/ios/ipa
